name: Container
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
  push:
    branches:
      - main
      - testing
permissions:
  attestations: write
  contents: read
  id-token: write
  packages: write
jobs:
  build-image:
    uses: SystemConsultantGroup/kubernetes/.github/workflows/build-image.yaml@48908370b0458339e50c2bbac2de6bbd9e7b4dde
    with:
      application: example
      workload: fe
      image: ghcr.io/systemconsultantgroup/kubernetes-example
    secrets:
      KUBERNETES_APP_ID: ${{ secrets.KUBERNETES_APP_ID }}
      KUBERNETES_APP_PRIVATE_KEY: ${{ secrets.KUBERNETES_APP_PRIVATE_KEY }}
